### ISSUE TITLE
Dapr>Spin>Dapr integration take 15-30sec for some requests

### ISSUE THREAD

**Issue by mikkelhegn** [ZEISS/enterprise-wasm#10]
More details to be provided by @KaiWalter based on testing.

**Comment by KaiWalter** [comment]
[runtime_profile_dapr_shared.csv](https://github.com/ZEISS/enterprise-wasm/files/13946919/runtime_profile_dapr_shared.csv)
[runtime_profile_dapr_sidecar.csv](https://github.com/ZEISS/enterprise-wasm/files/13946922/runtime_profile_dapr_sidecar.csv)

**Comment by KaiWalter** [comment]
fixed by switching to Azure Service Bus Premium - see
<https://github.com/ZEISS/enterprise-wasm/blob/main/analysis/2024-01-21%20order-ingress%20latency.md>
